//! Auto-generated protobuf types for plan/state machine communication.
//!
//! This module contains types generated by prost from the `.proto` files in `../proto/`.
//! Do not edit these files manually - they are regenerated on each build.
//!
//! # Usage
//!
//! ```ignore
//! use delta_kernel::proto_generated::*;
//!
//! // Create a scan node
//! let scan = ScanNode {
//!     file_type: scan_node::FileType::Parquet as i32,
//!     files: vec!["path/to/file.parquet".to_string()],
//!     schema: Some(schema),
//! };
//! ```

// Include the generated protobuf code from OUT_DIR
// The file is named after the protobuf package: delta.kernel -> delta.kernel.rs
include!(concat!(env!("OUT_DIR"), "/delta.kernel.rs"));

